pw8105_hw1_gw2442
================
2022-09-17

``` r
library(palmerpenguins)
library(tidyverse)
```

    ## ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──
    ## ✔ ggplot2 3.3.6      ✔ purrr   0.3.4 
    ## ✔ tibble  3.1.8      ✔ dplyr   1.0.10
    ## ✔ tidyr   1.2.0      ✔ stringr 1.4.1 
    ## ✔ readr   2.1.2      ✔ forcats 0.5.2 
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()

# Problem 1

### Loading the dataset:

``` r
data("penguins", package = "palmerpenguins")
```

### Names and values of important important variables in dataset “penguins”:

``` r
summary (penguins)
```

    ##       species          island    bill_length_mm  bill_depth_mm  
    ##  Adelie   :152   Biscoe   :168   Min.   :32.10   Min.   :13.10  
    ##  Chinstrap: 68   Dream    :124   1st Qu.:39.23   1st Qu.:15.60  
    ##  Gentoo   :124   Torgersen: 52   Median :44.45   Median :17.30  
    ##                                  Mean   :43.92   Mean   :17.15  
    ##                                  3rd Qu.:48.50   3rd Qu.:18.70  
    ##                                  Max.   :59.60   Max.   :21.50  
    ##                                  NA's   :2       NA's   :2      
    ##  flipper_length_mm  body_mass_g       sex           year     
    ##  Min.   :172.0     Min.   :2700   female:165   Min.   :2007  
    ##  1st Qu.:190.0     1st Qu.:3550   male  :168   1st Qu.:2007  
    ##  Median :197.0     Median :4050   NA's  : 11   Median :2008  
    ##  Mean   :200.9     Mean   :4202                Mean   :2008  
    ##  3rd Qu.:213.0     3rd Qu.:4750                3rd Qu.:2009  
    ##  Max.   :231.0     Max.   :6300                Max.   :2009  
    ##  NA's   :2         NA's   :2

### Size of the dataset:

``` r
nrow(penguins)
```

    ## [1] 344

``` r
ncol(penguins)
```

    ## [1] 8

The dataset has 344 rows and 8 columns.

### Mean flipper length:

``` r
data("penguins", package = "palmerpenguins")
mean(penguins$flipper_length_mm, na.rm = TRUE)
```

    ## [1] 200.9152

The mean flipper length is 200.92 mm.

### Scatterplot of `flipper_length_mm` (y) vs `bill_length_mm` (x)

``` r
library(tidyverse)
data("penguins", package = "palmerpenguins")
ggplot(penguins, aes (x = bill_length_mm , y = flipper_length_mm, na.rm = TRUE), 
       color = species) + geom_point()
```

    ## Warning: Removed 2 rows containing missing values (geom_point).

![](pw8105_hw1_gw2442_files/figure-gfm/yx_scatter-1.png)<!-- -->
